version: "3.7"
services:
  db: 
    image: mongo:latest
    container_name: sticky_note_db
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
  app:
    build: .
    container_name: sticky_note
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 3000:3000
    links:
      - db
    environment:
      - MongoURI=mongodb://db:27017/stickynote

    